sequence_lengths:
  - 4

alphabet:
  - JKLM

base_pairing_graphs:
  - 1

graph_path: /home/lgold/phd/research/projects/connectivity/rna_folding/snakemake_test/RNA4/

mapping_params:
  min_loop_size: 0
  suboptimal: 0
  structures_max: 1000
  base_pairing:
    - 2
    - 3
