
rule generate_genotype_space:
    output:
        "genotypes.txt"
    params:
        alphabet="AUGC",
        seq_len=1
    shell:
        "build_genotype_space.py " 
        "-a {params.alphabet} "
        "-l {params.seq_len} "
        "-o {output}"

rule nussinov_gp_map:
    input:
        "genotypes.txt"
    output:
        "{bp}/nussinov_gp_map.txt"  # regex to constrain to numbers and prevent matching subdirectory gp_map.txt
    params:
        graph_path="path/to/base_pairing_graph",
        min_loop_size=3,
        suboptimal=3,
        structures_max=10000,
        alphabet=None
    shell:
        "nussinov_gp_mapping.py "
        "-i {input} "
        "-o {output} "
        "-m {params.min_loop_size} "
        "-s {params.suboptimal} "
        "-z {params.structures_max} "
        "-g {params.graph_path} "
        "-a {params.alphabet} "
        "-p {wildcards.bp} "

rule extract_phenotype_list:
    input:
        "nussinov_gp_map.txt"
    output:
        "phenotypes.txt"
    shell:
        "cat {input} > tmp_phenotypes && " 
        "awk '{{print $1}}' {input} | sort | uniq > {output} && "
        "rm tmp_phenotypes"

rule extract_meta_list_of_phenotypes:
    input:
        expand("{some_dir}/phenotypes.txt", some_dir=["dir1, dir2"])
    output:
        "phenotypes.txt"
    shell:
        "cat {input} > tmp_phenotypes && " 
        "awk '{{print $1}}' {input} | sort | uniq > {output} && "
        "rm tmp_phenotypes"

# take phenotype file and randomly shuffle it using shuf function
rule create_random_ranking:
    input:
        "phenotypes.txt"
    output:
        "phenotype_ranking.txt"
    params:
        unviable=config["unviable"]
    shell:
        # remove unviable phenotype and shuffle rest
        "grep -Fxv '{params.unviable}' {input} | shuf > {output}; "
        "echo '{params.unviable}' >> {output}"  # attach unviable to bottom of ranking


rule pick_random_genotypes:
    output:
        "unfolded_genotypes.txt"
    input:
        "genotypes.txt"
    params:
        n_unfolded="........."
    run:
        import numpy as np
        gt_list = np.arange(0, 4**12)
        rand_g = np.random.choice(gt_list, size=14622554, replace=False)
        with open(output[0], "w") as f:
            for g in rand_g:
                f.write(str(g) + "\n")

                
rule flatten_gp_map:
    input:
        gp_map="nussinov_gp_map.txt",
        ranking="phenotype_ranking.txt"
    output:
        "gp_map.txt"
    params:
        unviable=config["unviable"]
    shell:
        "flatten_gp_map.py "
        "-i {input.gp_map} "
        "-r {input.ranking} "
        "-u {params.unviable} "
        "-o {output} "

rule flatten_gp_map_nc_cutoff:
    input:
        gp_map="nussinov_gp_map.txt",
        genotypes="genotypes.txt",
        ranking="phenotype_ranking.txt",
        unfolded_genotypes="unfolded_genotypes.txt"
    output:
        "gp_map.txt"
    params:
        nc_size_cutoff=1,
        unfolded="...",
        alphabet="AUGC"
    shell:
        "flatten_gp_map_nc_cutoff.py "
        "-i {input.gp_map} "
        "-r {input.ranking} "
        "-g {input.unfolded_genotypes} "
        "-t {input.genotypes} "
        "-c {params.nc_size_cutoff} "
        "-u {params.unfolded} "
        "-a {params.alphabet} "
        "-o {output} "

rule build_gpmap_python_object:
    input:
        gp_map="gp_map.txt",
        genotypes="genotypes.txt"
    output:
        "gp_map.pickle"
    params:
        alphabet=config["alphabet"],
        ignore_phenotype=config["unviable"]  # ignore unviable phenotype
    shell:
        "build_gpmap_pickle.py "
        "-f {input.gp_map} "
        "-g {input.genotypes} "
        "-a {params.alphabet} "
        "-i {params.ignore_phenotype} "
        "-o {output}"
