

rule plot_freq_over_peaks_vs_navigability:
    input:
        navigability=["gp_map/navig.txt"],  # list
        phenotype_distribution=["gp_map/phenotype_distribution.txt"],
        ruggedness=["gp_map/peak_sizes.txt"]
    output:
        "navigability_over_frequency_over_ruggedness_pop{pop_size}_seed{seed}.pdf"
    params:
        ruggedness_sample_size=1
    shell:
        "plot_navigability_over_freq_over_ruggedness.py "
        "-n {input.navigability} "
        "-f {input.phenotype_distribution} "
        "-r {input.ruggedness} "
        "-k {params.ruggedness_sample_size} "
        "-o {output} "

rule plot_path_categories:
    input:
        ["path_categories.pickle"]
    output:
        "analysis/path_categories.pdf"
    shell:
        "plot_path_categories.py "
        "-i {input} "
        "-o {output} "
